openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: Amazon Elasticsearch Service Domain API
  description: '<fullname>Amazon Elasticsearch Configuration Service</fullname> <p>Use the Amazon Elasticsearch Configuration API to create, configure, and manage Elasticsearch domains.</p> <p>For sample code that uses the Configuration API, see the <a href="https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-samples.html">Amazon Elasticsearch Service Developer Guide</a>. The guide also contains <a href="https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html">sample code for sending signed HTTP requests to the Elasticsearch APIs</a>.</p> <p>The endpoint for configuration service requests is region-specific: es.<i>region</i>.amazonaws.com. For example, es.us-east-1.amazonaws.com. For a current list of supported regions and endpoints, see <a href="http://docs.aws.amazon.com/general/latest/gr/rande.html#elasticsearch-service-regions" target="_blank">Regions and Endpoints</a>.</p>'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: es
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/es-2015-01-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://es.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Elasticsearch Service multi-region endpoint
- url: https://es.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon Elasticsearch Service multi-region endpoint
- url: http://es.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Elasticsearch Service endpoint for China (Beijing) and China (Ningxia)
- url: https://es.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon Elasticsearch Service endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Domain
paths:
  /2015-01-01/domain:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListDomainNames
      description: 'Returns the name of all Elasticsearch domains owned by the current user''s account. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDomainNamesResponse'
              examples:
                ListDomainNames200Example:
                  summary: Default ListDomainNames 200 response
                  x-microcks-default: true
                  value:
                    DomainNames: my-resource
        '480':
          description: BaseException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseException'
        '481':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
      parameters:
      - name: engineType
        in: query
        required: false
        description: ' Optional parameter to filter the output by domain engine type. Acceptable values are ''Elasticsearch'' and ''OpenSearch''. '
        schema:
          type: string
          enum:
          - OpenSearch
          - Elasticsearch
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      summary: Amazon OpenSearch List Domain Names
      tags:
      - Domain
  /2015-01-01/domain/{DomainName}/packages:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListPackagesForDomain
      description: Lists all packages associated with the Amazon ES domain.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPackagesForDomainResponse'
              examples:
                ListPackagesForDomain200Example:
                  summary: Default ListPackagesForDomain 200 response
                  x-microcks-default: true
                  value:
                    DomainPackageDetailsList: example-string
                    NextToken: example-string
        '480':
          description: BaseException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseException'
        '481':
          description: InternalException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalException'
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '483':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '484':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
      parameters:
      - name: DomainName
        in: path
        required: true
        description: The name of the domain for which you want to list associated packages.
        schema:
          type: string
          pattern: '[a-z][a-z0-9\-]+'
          description: 'The name of an Elasticsearch domain. Domain names are unique across the domains owned by an account within an AWS region. Domain names start with a letter or number and can contain the following characters: a-z (lowercase), 0-9, and - (hyphen).'
          minLength: 3
          maxLength: 28
      - name: maxResults
        in: query
        required: false
        description: Limits results to a maximum number of packages.
        schema:
          type: integer
          description: ' Set this value to limit the number of results returned. '
          maximum: 100
      - name: nextToken
        in: query
        required: false
        description: Used for pagination. Only necessary if a previous API call includes a non-null NextToken value. If provided, returns results for the next page.
        schema:
          type: string
          description: ' Paginated APIs accepts NextToken input to returns next page results and provides a NextToken output in the response which can be used by the client to retrieve more results. '
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      summary: Amazon OpenSearch List Packages for Domain
      tags:
      - Domain
components:
  schemas:
    ErrorType:
      type: string
    DomainName:
      type: string
      pattern: '[a-z][a-z0-9\-]+'
      description: 'The name of an Elasticsearch domain. Domain names are unique across the domains owned by an account within an AWS region. Domain names start with a letter or number and can contain the following characters: a-z (lowercase), 0-9, and - (hyphen).'
      minLength: 3
      maxLength: 28
    PackageVersion:
      type: string
    ReferencePath:
      type: string
    DomainInfo:
      type: object
      properties:
        DomainName:
          allOf:
          - $ref: '#/components/schemas/DomainName'
          - description: ' Specifies the <code>DomainName</code>.'
        EngineType:
          allOf:
          - $ref: '#/components/schemas/EngineType'
          - description: ' Specifies the <code>EngineType</code> of the domain.'
    DomainPackageDetailsList:
      type: array
      items:
        $ref: '#/components/schemas/DomainPackageDetails'
    DomainPackageStatus:
      type: string
      enum:
      - ASSOCIATING
      - ASSOCIATION_FAILED
      - ACTIVE
      - DISSOCIATING
      - DISSOCIATION_FAILED
    BaseException: {}
    DomainPackageDetails:
      type: object
      properties:
        PackageID:
          allOf:
          - $ref: '#/components/schemas/PackageID'
          - description: Internal ID of the package.
        PackageName:
          allOf:
          - $ref: '#/components/schemas/PackageName'
          - description: User specified name of the package.
        PackageType:
          allOf:
          - $ref: '#/components/schemas/PackageType'
          - description: Currently supports only TXT-DICTIONARY.
        LastUpdated:
          allOf:
          - $ref: '#/components/schemas/LastUpdated'
          - description: Timestamp of the most-recent update to the association status.
        DomainName:
          allOf:
          - $ref: '#/components/schemas/DomainName'
          - description: Name of the domain you've associated a package with.
        DomainPackageStatus:
          allOf:
          - $ref: '#/components/schemas/DomainPackageStatus'
          - description: State of the association. Values are ASSOCIATING/ASSOCIATION_FAILED/ACTIVE/DISSOCIATING/DISSOCIATION_FAILED.
        PackageVersion:
          $ref: '#/components/schemas/PackageVersion'
        ReferencePath:
          allOf:
          - $ref: '#/components/schemas/ReferencePath'
          - description: The relative path on Amazon ES nodes, which can be used as synonym_path when the package is synonym file.
        ErrorDetails:
          allOf:
          - $ref: '#/components/schemas/ErrorDetails'
          - description: Additional information if the package is in an error state. Null otherwise.
      description: Information on a package that is associated with a domain.
    AccessDeniedException: {}
    ListDomainNamesResponse:
      type: object
      properties:
        DomainNames:
          allOf:
          - $ref: '#/components/schemas/DomainInfoList'
          - description: List of domain names and respective engine types.
      description: The result of a <code>ListDomainNames</code> operation. Contains the names of all domains owned by this account and their respective engine types.
    InternalException: {}
    LastUpdated:
      type: string
      format: date-time
    DomainInfoList:
      type: array
      description: ' Contains the list of Elasticsearch domain information.'
      items:
        $ref: '#/components/schemas/DomainInfo'
    ErrorDetails:
      type: object
      properties:
        ErrorType:
          $ref: '#/components/schemas/ErrorType'
        ErrorMessage:
          $ref: '#/components/schemas/ErrorMessage'
    ErrorMessage:
      type: string
    PackageName:
      type: string
      pattern: '[a-z][a-z0-9\-]+'
      minLength: 3
      maxLength: 28
    String:
      type: string
    PackageID:
      type: string
    PackageType:
      type: string
      enum:
      - TXT-DICTIONARY
    EngineType:
      type: string
      enum:
      - OpenSearch
      - Elasticsearch
    ListPackagesForDomainResponse:
      type: object
      properties:
        DomainPackageDetailsList:
          allOf:
          - $ref: '#/components/schemas/DomainPackageDetailsList'
          - description: List of <code>DomainPackageDetails</code> objects.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: Pagination token that needs to be supplied to the next call to get the next page of results.
      description: ' Container for response parameters to <code> <a>ListPackagesForDomain</a> </code> operation. '
    ResourceNotFoundException: {}
    ValidationException: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/es/
